# The URL the site will be built for
base_url = "https://example.com"

compile_sass = true
build_search_index = true
minify_html = true

# Ignores any backups or template files
ignored_content = [ "template.*", "backup.*" ]

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
    highlight_code = true
    highlight_theme = "gruvbox-dark"

[extra]
# Put all your custom variables here
